### ISSUE TITLE
Move logic from _process_message_queue to Dialogue class

### ISSUE THREAD

**Issue by monijames** [jrriehl/uAgents#3]
The `_process_message_queue` function is a bit too long and complicated and I wonder if some of the logic related to the Dialogue could be moved to the Dialogue class.

**Comment by jrriehl** [comment]
I'm sorry, but in order to provide an accurate solution to your issue, I would need access to the relevant source code. Specifically, I would require the `_process_message_queue` method's implementation and the `Dialogue` class definition. Could you please provide these code snippets?

**Comment by monijames** [comment]
1. This code snippet is relevant because it's the main part where the `_process_message_queue` function handles the logic of a Dialogue. This is a key place where some logic could be moved to the `Dialogue` class to reduce complexity.

Github links:
<a href=https://github.com/fetchai/uAgents/blob/main/python/src/uagents/context.py#L461-L490>python/src/uagents/context.py#L461-L490</a>


2. This code snippet is relevant because it shows how the Dialogue state is updated in the `Dialogue` class. This could be a target area to move more logic to from the `_process_message_queue` function.

Github links:
<a href=https://github.com/fetchai/uAgents/blob/main/python/src/uagents/experimental/dialogues/__init__.py#L306-L314>python/src/uagents/experimental/dialogues/__init__.py#L306-L314</a>

3. This code snippet is relevant because it shows the logic of handling received messages in the `_process_message_queue` function. Some of this logic could potentially be moved to the `Dialogue` class.

Github links:
<a href=https://github.com/fetchai/uAgents/blob/main/python/src/uagents/agent.py#L943-L977>python/src/uagents/agent.py#L943-L977</a>

4. This code snippet is relevant because it shows how a new message is added to the Dialogue. This could be potentially be done within the `Dialogue` class itself.

Github links:
<a href=https://github.com/fetchai/uAgents/blob/main/python/src/uagents/context.py#L492-L503>python/src/uagents/context.py#L492-L503</a>

**Comment by jrriehl** [comment]
This model's maximum context length is 8192 tokens. However, your messages resulted in 21171 tokens. Please reduce the length of the messages.

**Comment by jrriehl** [comment]
This model's maximum context length is 8192 tokens. However, your messages resulted in 20293 tokens. Please reduce the length of the messages.

**Comment by jrriehl** [comment]
I wasn't able to make the requested changes. Can you help me out with some more details?
